sc1= SkinCondition.create(skintype: "Dry", skinissue: "Acne")
sc2= SkinCondition.create(skintype: "Dry", skinissue: "Eczema")
sc3= SkinCondition.create(skintype: "Dry", skinissue: "Dark Spots")
sc4= SkinCondition.create(skintype: "Dry", skinissue: "Wrinkles")
sc5= SkinCondition.create(skintype: "Oily", skinissue: "Acne")
sc6= SkinCondition.create(skintype: "Oily", skinissue: "Eczema")
sc7= SkinCondition.create(skintype: "Oily", skinissue: "Dark Spots")
sc8= SkinCondition.create(skintype: "Oily", skinissue: "Wrinkles")

p1= Product.create(name: "Clean and Clear Advantage Acne Control", price: 14, skinconditions: sc1)
p2= Product.create(name: "Neutrogena Hydro Boost Water Gel", price: 8, skinconditions: sc2)
p3= Product.create(name: "Glossier Milky Jelly Cleanser", price: 14, skinconditions: sc3)
p4= Product.create(name: "Neutrogena Rapid Wrinkle Repair Night Moisturizer", price: 24, skinconditions:sc4)
p5= Product.create(name: "The Ordinary Salicylic Acid", price: 10, skinconditions:sc5)
p6= Product.create(name: "Skinfix Dermatitis Face Balm", price: 14, skinconditions:sc6)
p7= Product.create(name: "La Roche-Posay Toleriane Purifying Foaming Cleanser", price: 18, skinconditions:sc7)
p8= Product.create(name: "Lancome Hydra Zen Anti-Stress Glow Liquid", price: 45, skinconditions: sc8)

user1 = User.create(name:"Maria", skinconditions: sc8, products: p8 )			
user2 = User.create(name:"Sam", skinconditions: sc1, products: p1 )			
user3 = User.create(name:"Anna", skinconditions: sc3, products: p3 )			
user4 = User.create(name:"Greg", skinconditions:sc7, products: p7 )			
user5 = User.create(name:"Charlotte", skinconditions: sc2, products: p2 )			
user6 = User.create(name:"Nina", skinconditions: sc6, products: p6 )			
user7 = User.create(name:"Remy", skinconditions: sc2, products: p2 )			
user8 = User.create(name:"Brandy", skinconditions:sc4, products: p4 )			
user9 = User.create(name:"Nicky", skinconditions: sc5, products: p5 )			
user10 = User.create(name:"Alex", skinconditions: sc2, products: p2 )			